### ISSUE TITLE
KeyError: 'admin_user'

### ISSUE THREAD

**Issue by l1ph0x** [proversity-org/rocket-chat-extension#34]
I tried installing rocket extension (rocketc-xblock) on the Native installation of Open edX (open-release/ginkgo.master) but got the error when I tried to access it from CMS

![rkt](https://user-images.githubusercontent.com/13763779/42034572-86fca648-7af1-11e8-8fee-87136c6d917e.png)

--------------------------------------------------------------------------
The the commands I used for installation are as follows:
sudo -H -u edxapp bash
source /edx/app/edxapp/edxapp_env
cd /edx/app/edxapp/edx-platform
git clone https://github.com/proversity-org/rocket-chat-extension.git
pip install -e . 

Am I doing anything wrong?
--------------------------------------------------------------------------
Attchaed below, are the err log (from CMS)

Jun 28 05:29:44 ubuntu [service_variant=cms][contentstore.views.preview][env:sandbox] WARNING [ubuntu  2590] [preview.py:318] - Unable to render author_view for <VerticalBlockWithMixins @6E5C visible_to_staff_only=False, graded=False, annotation_token_secret=u'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', hide_after_due=False, giturl=None, edxnotes=False, source_file=None, course_edit_method=u'Studio', default_tab=None, children=[BlockUsageLocator(CourseLocator(u'edX', u'DemoX', u'Demo_Course', None, None), u'rocketc', u'1f6ea8dcb4564b7e82dc59ce7dde2ade')], in_entrance_exam=False, showanswer=u'attempted', display_name=u'Unit', video_speed_optimizations=True, graceperiod=datetime.timedelta(0, 18000), format=None, due=None, start=datetime.datetime(2013, 2, 5, 5, 0, tzinfo=tzutc()), xml_attributes={}, video_bumper={}, max_attempts=None, parent=BlockUsageLocator(CourseLocator(u'edX', u'DemoX', u'Demo_Course', None, None), u'sequential', u'fd5a6ff504d84366b99f7a07a5b94847'), tags=[], matlab_api_key=None, xqa_key=u'qaijS3UatK020Wc0sfCtFe0V6jpB4d64', is_entrance_exam=False, annotation_storage_url=u'http://your_annotation_storage.com', use_latex_compiler=False, days_early_for_beta=None, show_correctness=u'always', static_asset_path=u'', name=None, hide_from_toc=False, group_access={}, rerandomize=u'never', user_partitions=[], chrome=None, edxnotes_visibility=True, position=None, show_reset_button=False, self_paced=False>
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/preview.py", line 316, in get_preview_fragment
    fragment = module.render(preview_view, context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/core.py", line 202, in render
    return self.runtime.render(self, view, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1894, in render
    return self.__getattr__('render')(block, view_name, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1302, in render
    return super(MetricsMixin, self).render(block, view_name, context=context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/runtime.py", line 808, in render
    frag = view_fn(context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/vertical_block.py", line 99, in author_view
    self.render_children(context, fragment, can_reorder=True, can_add=True)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/studio_editable.py", line 26, in render_children
    rendered_child = child.render(StudioEditableModule.get_preview_view_name(child), context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/core.py", line 202, in render
    return self.runtime.render(self, view, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1894, in render
    return self.__getattr__('render')(block, view_name, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1302, in render
    return super(MetricsMixin, self).render(block, view_name, context=context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/runtime.py", line 808, in render
    frag = view_fn(context)
  File "/edx/app/edxapp/edx-platform/rocket-chat-extension/rocketc/rocketc.py", line 97, in student_view
    return self.author_view(context)
  File "/edx/app/edxapp/edx-platform/rocket-chat-extension/rocketc/rocketc.py", line 117, in author_view
    self.api_rocket_chat.convert_to_private_channel("general")
  File "/edx/app/edxapp/edx-platform/rocket-chat-extension/rocketc/rocketc.py", line 159, in api_rocket_chat
    user = self.xblock_settings["admin_user"]
KeyError: 'admin_user'

**Comment by l1ph0x** [comment]
Oh, sorry. Only after creating this issue I saw the [pull request #33](https://github.com/proversity-org/rocket-chat-extension/pull/33/commits/d2b12e254553613a5f004dc028ed397153b90064)
